### ISSUE TITLE
GitHub Actions / Docker-Based Blue-Green Deployment

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#307]
It should be possible to automate deployment using GitHub Actions, more convenient and less prone to human error (unless the human error is in the deployment of Actions...)

In any case, it is desirable to minimise downtime during the rebuilding of containers. The `web` service, for example, currently takes about 10 minutes. A "Blue Green" deployment might help.

If "blue" is existing, then "green" would have its own `web` container but re-use "blue" containers for other services.

Combine with #333.

For example:

```
version: '3'
services:
  web:
    image: your-app-image:new-version
    ports:
      - "8002:8003"  # Use a different port from the Blue environment
    # other configurations
    
  # Reuse existing containers
  postgres:
    external: true  # Assuming you are using the same PostgreSQL container
    
  redis:
    external: true  # Assuming you are using the same Redis container
    
  webpack:
    external: true  # Assuming you are using the same Webpack container

```

Routing through Nginx then needs to be switched, but that too might be automated.
